version: "3.9"

services:
  db:
    image: "postgres:latest"
    container_name: "postgresql"
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depens_on:
      - db
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
