version: 3.3
services:
  db:
    image: postgres:latest
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data/:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: 33m
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - 5050:80
    volumes: 
      - ./pgadmin:/root/.pgadmin
    logging:
      driver: json-file
      options:
        max-size: 33m
